export const seats = [
	{ id: "A1", status: true },
	{ id: "A2", status: false },
	{ id: "A3", status: false },
	{ id: "A4", status: true },
	{ id: "B1", status: true },
	{ id: "B2", status: false },
	{ id: "B3", status: false },
	{ id: "B4", status: true },
	{ id: "C1", status: true },
	{ id: "C2", status: true },
	{ id: "C3", status: false },
	{ id: "C4", status: false },
	{ id: "D1", status: true },
	{ id: "D2", status: true },
	{ id: "D3", status: false },
	{ id: "D4", status: false },
];
